### ISSUE TITLE
sublime text snippets 관련해서 질문드립니다!

### ISSUE THREAD

**Issue by hanyazz** [yamoo9-Lab/sass-workflow#3]
https://github.com/yamoo9/Sublime-text-User-Snippets
이 곳에 저장 된 snippet을 옮겨넣었는데

ul>li*7>a[href="/"]>img 

탭이 안 먹네요 ㅠㅠ 다른 설정 파일이 있는건가요?

**Comment by yamoo9** [comment]
![Emmet](http://emmet.io/-/4076541266/i/logo.svg)

[Emmet](http://emmet.io/) 을 설치하셔야 합니다. :-) 제가 공유해드린 `Snippet`과는 큰 관련이 없습니다. ^^;
[Sublime Text에 Emmet 설치하는 방법](https://github.com/sergeche/emmet-sublime#how-to-install)을 참고해서 설치해주시고, 잘 안되시면 수업 시간에 이야기주세요~

**Comment by hanyazz** [comment]
감사합니다! ^_^
